---
# tasks file for apache

 - include_vars: "{{ ansible_os_family }}.yml"
 
 - include: Install_Redhat.yml
   when: ansible_os_family == 'Redhat'

 - include: Install_Ubuntu.yml
   when: ansible_os_family == 'Ubuntu' 

 - name: To copy a file from Ansible control server to client
   copy: src=/opt/ansible_code/roles/apache/files/index.html dest=/var/www/html/index.html owner=root group=root
   notify: restart apache

 - name: To register the apache webserver as startup service
   service: name=httpd enabled=yes

 - name: To start my apache webserver 
   service: name=httpd state=started
